// packages/react/src/sarmal.tsx
"use client";
import type { SarmalProps } from "./types";

import { useLayoutEffect, memo } from "react";
import { useSarmal } from "./use-sarmal";
import { useRenderOptions } from "./use-render-options";

const SarmalInner = ({
  curve,
  className,
  style,
  trailColor,
  morphDuration,
  morphStrategy,
  morphEasing,
  morphAlign,
  onReady,
  skeletonColor,
  headColor,
  trailStyle,
  width,
  height,
  headRadius,
  trailLength,
  trailWidth,
  autoStart,
  initialPhase,
  pauseOnHidden,
}: SarmalProps) => {
  const { canvasRef, instance } = useSarmal(
    curve,
    {
      ...(skeletonColor !== undefined && { skeletonColor }),
      ...(trailColor !== undefined && { trailColor }),
      ...(headColor !== undefined && { headColor }),
      ...(trailStyle !== undefined && { trailStyle }),
    },
    {
      ...(width !== undefined && { width }),
      ...(height !== undefined && { height }),
      ...(headRadius !== undefined && { headRadius }),
      ...(trailLength !== undefined && { trailLength }),
      ...(autoStart !== undefined && { autoStart }),
      ...(initialPhase !== undefined && { initialPhase }),
      ...(pauseOnHidden !== undefined && { pauseOnHidden }),
    },
    morphDuration !== undefined ||
      morphStrategy !== undefined ||
      morphEasing !== undefined ||
      morphAlign !== undefined
      ? {
          ...(morphDuration !== undefined && { morphDuration }),
          ...(morphStrategy !== undefined && { morphStrategy }),
          ...(morphEasing !== undefined && { morphEasing }),
          ...(morphAlign !== undefined && { morphAlign }),
        }
      : undefined,
  );

  useRenderOptions(instance, trailColor, skeletonColor, headColor, trailStyle, trailWidth);

  useLayoutEffect(() => {
    if (instance.current) {
      onReady?.(instance.current);
    }
  }, []);

  return <canvas ref={canvasRef} className={className} style={style} />;
};

export const Sarmal = memo(SarmalInner);
export type { SarmalProps };

// packages/svelte/src/Sarmal.svelte
<script lang="ts">
  import type {
    CurveDef,
    SarmalInstance,
  } from "@sarmal/core";
  import type { SarmalProps } from "./types";

  import { untrack } from "svelte";
  import { createSarmal } from "@sarmal/core";
  import { resolveCanvasSize } from "./utils";

  let {
    curve,
    class: className = "",
    style: styleStr = "",
    trailColor,
    skeletonColor,
    headColor,
    trailStyle,
    morphDuration,
    morphStrategy,
    morphEasing,
    morphAlign,
    instance = $bindable(null as SarmalInstance | null),
    trailLength,
    headRadius,
    trailWidth,
    autoStart,
    initialPhase,
    pauseOnHidden,
    width,
    height,
    onready,
  }: SarmalProps = $props();

  let canvas = $state<HTMLCanvasElement | null>(null);
  let committedCurve: CurveDef | null = null;

  $effect(() => {
    const c = canvas;
    if (!c) {
      return;
    }

    const { width: w, height: h } = resolveCanvasSize(c, width, height);
    c.width = w;
    c.height = h;

    const initCurve = untrack(() => curve);
    const initRuntimeOpts = untrack(() => ({
      ...(trailColor !== undefined && { trailColor }),
      ...(skeletonColor !== undefined && { skeletonColor }),
      ...(headColor !== undefined && { headColor }),
      ...(trailStyle !== undefined && { trailStyle }),
      ...(trailWidth !== undefined && { trailWidth }),
    }));

    const inst = createSarmal(c, initCurve, {
      ...initRuntimeOpts,
      ...(trailLength !== undefined && { trailLength }),
      ...(headRadius !== undefined && { headRadius }),
      ...(autoStart !== undefined && { autoStart }),
      ...(initialPhase !== undefined && { initialPhase }),
      ...(pauseOnHidden !== undefined && { pauseOnHidden }),
    });

    instance = inst;
    committedCurve = initCurve;

    return () => {
      inst.destroy();
      instance = null;
      committedCurve = null;
    };
  });

  $effect(() => {
    if (committedCurve == null) {
      return;
    }

    if (curve === committedCurve) {
      return;
    }

    committedCurve = curve;
    instance
      ?.morphTo(curve, {
        ...(morphDuration != null && { duration: morphDuration }),
        ...(morphStrategy != null && { morphStrategy }),
        ...(morphEasing != null && { easing: morphEasing }),
        ...(morphAlign != null && { align: morphAlign }),
      })
      .catch(() => {});
  });

  $effect(() => {
    const inst = instance;
    if (!inst) {
      return;
    }

    inst.setRenderOptions({
      ...(trailColor !== undefined && { trailColor }),
      ...(skeletonColor !== undefined && { skeletonColor }),
      ...(headColor !== undefined ? { headColor } : { headColor: null }),
      ...(trailStyle !== undefined && { trailStyle }),
      ...(trailWidth !== undefined && { trailWidth }),
    });
  });

  $effect(() => {
    const inst = instance;
    if (!inst) {
      return;
    }

    onready?.(inst);
  });
</script>

<canvas bind:this={canvas} class={className} style={styleStr}></canvas>
